/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as BriefIdRouteImport } from './routes/brief/$id'
import { Route as SessionIdRouteImport } from './routes/session/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIdRoute = BriefIdRouteImport.update({
  id: '/brief/$id',
  path: '/brief/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/brief/$id': typeof BriefIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/brief/$id': typeof BriefIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/brief/$id': typeof BriefIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/transcribe' | '/brief/$id' | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/transcribe' | '/brief/$id' | '/session/$id'
  id: '__root__' | '/' | '/api/transcribe' | '/brief/$id' | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  BriefIdRoute: typeof BriefIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$id': {
      id: '/brief/$id'
      path: '/brief/$id'
      fullPath: '/brief/$id'
      preLoaderRoute: typeof BriefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  BriefIdRoute: BriefIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
